cat \
  "01_Introduction.md" \
  "02_foundations_of_system_design.md" \
  "03_tradeoffs.md" \
  "04_dns.md" \
  "05_cdn.md" \
  "06_load_balancer.md" \
  "07_reverse_proxy.md" \
  "08_distributed_systems.md" \
  "09_database.md" \
  "10_cache.md" \
  "11_asynchronous.md" \
  "12_rest.md" \
  "13_security.md" \
  "14_back-of-the-envelope.md" \
  "15_interview_questions.md" \
  "16_real_world_architectures.md" \
  "17_under_development.md" \
  "18_credits.md" \
> new.md
